In [1]:
import pandas as pd

In [5]:
import os

path = r"C:\Users\UserComp\Data_Analytics\Amazon_Bestselling_Books\data"

os.listdir(path)

['.ipynb_checkpoints', 'archive (2).zip']

In [6]:
import zipfile

zip_path = r"C:\Users\UserComp\Data_Analytics\Amazon_Bestselling_Books\data\archive (2).zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(r"C:\Users\UserComp\Data_Analytics\Amazon_Bestselling_Books\data")

In [7]:
os.listdir(path)

['.ipynb_checkpoints', 'archive (2).zip', 'bestsellers with categories.csv']

In [8]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\UserComp\Data_Analytics\Amazon_Bestselling_Books\data\bestsellers with categories.csv"
)

In [9]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [10]:
df.shape

(550, 7)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    str
 1   Author       550 non-null    str
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    str
dtypes: float64(1), int64(3), str(3)
memory usage: 30.2 KB

In [12]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [15]:
df['Genre'].value_counts()

Genre
Non Fiction    310
Fiction        240
Name: count, dtype: int64

In [16]:
df['Year'].value_counts().sort_index()

Year
2009    50
2010    50
2011    50
2012    50
2013    50
2014    50
2015    50
2016    50
2017    50
2018    50
2019    50
Name: count, dtype: int64

In [17]:
df['Author'].value_counts().head(10)

Author
Jeff Kinney                           12
Suzanne Collins                       11
Rick Riordan                          11
Gary Chapman                          11
American Psychological Association    10
Dr. Seuss                              9
Gallup                                 9
Rob Elliott                            8
Stephenie Meyer                        7
Dav Pilkey                             7
Name: count, dtype: int64

In [18]:
df = df.rename(columns={
    'Name': 'book_name',
    'Author': 'author',
    'User Rating': 'user_rating',
    'Reviews': 'reviews',
    'Price': 'price',
    'Year': 'year',
    'Genre': 'genre'
})

In [19]:
df.head()

,book_name,author,user_rating,reviews,price,year,genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [21]:
df.groupby('genre')['user_rating'].agg(['count', 'mean', 'median'])

             count      mean  median
genre
Fiction        240  4.648333     4.7
Non Fiction    310  4.595161     4.6

In [25]:
df.to_csv(
    r"C:\Users\UserComp\Data_Analytics\Amazon_Bestselling_Books\data\books_clean.csv",
    index=False
)